# Generated by Django 5.0.7 on 2024-07-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs_app', '0002_rename_reader_contac_reader_reader_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=100)),
                ('published_year', models.IntegerField()),
                ('copies_available', models.IntegerField(default=1)),
            ],
        ),
    ]
